# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  tradie-server:
    build:
      context: .
    command: bash -c "python manage.py migrate && gunicorn services_core.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    ports:
      - 8001:8000
    depends_on:
     tradie-services-db:
        condition: service_healthy
    networks:
      - tradie-app-network
  tradie-services-db:
    image: postgres
    restart: always
    user: ${DB_USER}
    volumes:
      - tradie-services-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    expose:
      - 5432
    ports: 
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tradie-app-network
volumes:
  tradie-services-db-data:
    # secrets:
    #   db-password:
    #     file: db/password.txt

networks:
  tradie-app-network:
    driver: bridge